# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options

zeebe.client:
  #  broker.gatewayAddress: 127.0.0.1:26500
  #  security.plaintext: true
  cloud:
    region: XXX
    clusterId: XXX
    clientId: XXX
    clientSecret: XXX
logging.level:
  root: INFO
  my.test: DEBUG

